# Generated by Django 5.2 on 2025-04-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_super_admin',
            new_name='is_org_staff',
        ),
    ]
