# Generated by Django 5.2 on 2025-04-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('wallet', '0009_alter_staffprofile_profile_image_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.companykyc'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.companykyc'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.companykyc'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.companykyc'),
        ),
        migrations.AddField(
            model_name='operation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.companykyc'),
        ),
        migrations.AddField(
            model_name='operationcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.companykyc'),
        ),
    ]
