# Generated by Django 5.2 on 2025-04-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_event_company_eventcategory_company_expense_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
