# Generated by Django 5.2 on 2025-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_approved_expense_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
