# Generated by Django 5.2 on 2025-04-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expense_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
