# Generated by Django 5.2 on 2025-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_event_approved_event_paid_operation_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='project_lead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
