# Generated by Django 5.2 on 2025-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_operation_project_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
