# Generated by Django 5.2 on 2025-05-09 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_alter_event_budget_alter_operation_budget'),
        ('wallet', '0017_remove_transaction_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='wallet.wallet'),
        ),
    ]
