# Generated by Django 5.2 on 2025-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0013_event_updated_by_operation_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
