# Generated by Django 5.2 on 2025-05-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_expense_declined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
