# Generated by Django 5.2 on 2025-08-29 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0017_activationcategory_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.activation'),
        ),
    ]
