# Generated by Django 5.2 on 2025-08-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0018_expense_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='budget_file',
            field=models.FileField(blank=True, null=True, upload_to='budget'),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_file',
            field=models.FileField(blank=True, null=True, upload_to='budget'),
        ),
        migrations.AddField(
            model_name='operation',
            name='budget_file',
            field=models.FileField(blank=True, null=True, upload_to='budget'),
        ),
    ]
