# Generated by Django 5.2 on 2025-08-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0019_activation_budget_file_event_budget_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='batch_disbursement_type',
            field=models.BooleanField(default=False),
        ),
    ]
