# Generated by Django 5.2 on 2025-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(blank=True, choices=[('KES', 'KES'), ('UGX', 'UGX')], max_length=10, null=True),
        ),
    ]
