# Generated by Django 5.2 on 2025-04-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_notification_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykyc',
            name='kra_pin',
            field=models.FileField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='companykyc',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='kyc'),
        ),
    ]
