# Generated by Django 5.2 on 2025-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_companykyc_kra_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companykyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
