# Generated by Django 5.2 on 2025-04-17 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_companykyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykyc',
            name='kra_pin',
            field=models.FileField(blank=True, null=True, upload_to='kyc', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='companykyc',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='kyc', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='companykyc',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='kyc', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
