# Generated by Django 5.2 on 2025-04-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_staffprofile_profile_image_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='company',
        ),
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
    ]
