# Generated by Django 5.2 on 2025-04-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_companykyc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.companykyc'),
        ),
    ]
