# Generated by Django 5.2 on 2025-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_wallet_company_alter_companykyc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
