# Generated by Django 5.2 on 2025-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_remove_transaction_reciever_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='amount',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('None', 'None'), ('Transfer', 'Transfer'), ('Sent Expense request', 'Sent Expense request'), ('Approved Expense request', 'Approved Expense request'), ('Sent Payment Request', 'Sent Payment Request'), ('Received Payment Request', 'Received Payment Request'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='none', max_length=100),
        ),
    ]
