# Generated by Django 5.2 on 2025-06-05 08:43

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_remove_notification_amount_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=20, prefix='SPNDY', unique=True),
        ),
    ]
