# Generated by Django 5.2 on 2025-06-15 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_smslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='company',
        ),
        migrations.AddField(
            model_name='smslog',
            name='cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='notification_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['phone_number', '-sent_at'], name='wallet_smsl_phone_n_c0872a_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status', '-sent_at'], name='wallet_smsl_status_a7f349_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['notification_type', '-sent_at'], name='wallet_smsl_notific_4a1558_idx'),
        ),
    ]
