# Generated by Django 5.2 on 2025-06-16 10:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_alter_smslog_options_remove_smslog_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('B2B', 'Business to Business'), ('TRANSACTION_STATUS', 'Transaction Status Query'), ('ACCOUNT_BALANCE', 'Account Balance Query'), ('REVERSAL', 'Transaction Reversal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout'), ('REVERSED', 'Reversed')], default='PENDING', max_length=15)),
                ('merchant_request_id', models.CharField(blank=True, help_text='STK Push merchant request ID', max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, help_text='STK Push checkout request ID', max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, help_text='M-Pesa conversation ID', max_length=100, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, help_text='Originator conversation ID', max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa receipt number', max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=50, null=True)),
                ('command_id', models.CharField(blank=True, choices=[('CustomerPayBillOnline', 'Customer Pay Bill Online'), ('CustomerBuyGoodsOnline', 'Customer Buy Goods Online'), ('BusinessPayment', 'Business Payment'), ('SalaryPayment', 'Salary Payment'), ('PromotionPayment', 'Promotion Payment'), ('BusinessPayBill', 'Business Pay Bill'), ('BusinessBuyGoods', 'Business Buy Goods'), ('TransactionStatusQuery', 'Transaction Status Query'), ('AccountBalance', 'Account Balance'), ('TransactionReversal', 'Transaction Reversal')], max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('party_a', models.CharField(blank=True, help_text='Sender party', max_length=15, null=True)),
                ('party_b', models.CharField(blank=True, help_text='Receiver party', max_length=15, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Customer phone number', max_length=15, null=True)),
                ('account_reference', models.CharField(blank=True, help_text='Account reference/Bill reference', max_length=100, null=True)),
                ('transaction_desc', models.TextField(blank=True, help_text='Transaction description', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Transaction remarks', null=True)),
                ('occasion', models.CharField(blank=True, help_text='Transaction occasion', max_length=100, null=True)),
                ('callback_data', models.JSONField(blank=True, help_text='Complete callback response data', null=True)),
                ('result_code', models.CharField(blank=True, help_text='Result code from callback', max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, help_text='Result description from callback', null=True)),
                ('customer_message', models.TextField(blank=True, help_text='Message sent to customer', null=True)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reserved_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('uncleared_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('original_transaction_id', models.CharField(blank=True, help_text='Original transaction ID for reversals', max_length=50, null=True)),
                ('reversal_reason', models.TextField(blank=True, help_text='Reason for reversal', null=True)),
                ('response_code', models.CharField(blank=True, help_text='API response code', max_length=10, null=True)),
                ('response_description', models.TextField(blank=True, help_text='API response description', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code if transaction failed', max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if transaction failed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client user agent', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether transaction has been processed by business logic')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'db_table': 'mpesa_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_type', models.CharField(help_text='Type of callback (STK, C2B, B2C, etc.)', max_length=50)),
                ('raw_data', models.JSONField(help_text='Raw callback data')),
                ('ip_address', models.GenericIPAddressField(help_text='Callback source IP')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_logs', to='wallet.mpesatransaction')),
            ],
            options={
                'db_table': 'mpesa_callback_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='mpesa_trans_transac_1fca2a_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='mpesa_trans_mpesa_r_39856b_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone_number'], name='mpesa_trans_phone_n_93d554_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='mpesa_trans_checkou_3d1894_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['conversation_id'], name='mpesa_trans_convers_96ba8d_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['created_at'], name='mpesa_trans_created_96a380_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['account_reference'], name='mpesa_trans_account_e978ee_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallbacklog',
            index=models.Index(fields=['callback_type'], name='mpesa_callb_callbac_71935d_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallbacklog',
            index=models.Index(fields=['processed'], name='mpesa_callb_process_e4b8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallbacklog',
            index=models.Index(fields=['created_at'], name='mpesa_callb_created_3c1af7_idx'),
        ),
    ]
