# Generated by Django 5.2 on 2025-06-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_mpesatransaction_mpesacallbacklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.companykyc'),
        ),
    ]
