# Generated by Django 5.2 on 2025-06-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_mpesatransaction_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacallbacklog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback', to='wallet.companykyc'),
        ),
    ]
