# Generated by Django 5.2 on 2025-06-25 08:37

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_mpesacallbacklog_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=7, max_length=25, null=True, prefix=''),
        ),
    ]
