# Generated by Django 5.2 on 2025-07-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0029_transaction_completed_at_transaction_failure_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='parent_transaction',
        ),
    ]
