# Generated by Django 5.2 on 2025-07-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0031_transactionfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfee',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transaction'),
        ),
    ]
