# Generated by Django 5.2 on 2025-07-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0032_transactionfee_parent_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='conversation_id',
            field=models.CharField(blank=True, help_text='M-Pesa conversation ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='originator_conversation_id',
            field=models.CharField(blank=True, help_text='Originator conversation ID', max_length=100, null=True),
        ),
    ]
