# Generated by Django 5.2 on 2025-08-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0034_client_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('EVENT', 'EVENT'), ('OPERATIONS', 'OPERATIONS'), ('ACTIVATION', 'ACTIVATION'), ('EMERGENCY', 'EMERGENCY')], default='PRIMARY', max_length=10),
        ),
    ]
