# Generated by Django 5.2 on 2025-08-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0035_alter_wallet_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
