# Generated by Django 5.2 on 2025-10-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0036_alter_transaction_transaction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
