# Generated by Django 5.2 on 2025-10-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0038_alter_transactionfee_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companykyc',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('event_organization', 'Event Organization'), ('agency', 'Agency')], max_length=100, null=True),
        ),
    ]
