# Generated by Django 5.2 on 2025-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0039_companykyc_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
    ]
