# Generated by Django 5.2 on 2025-11-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0040_role_is_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa transaction code', max_length=255, null=True),
        ),
    ]
