# Generated by Django 5.2 on 2025-12-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0041_transaction_mpesa_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_party_public_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_party_public_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
